In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3], dtype='f') 
x.dtype

dtype('float32')

In [5]:
# x = np.array([1, 2, 3], dtype='i2') 
x = np.array([1, 2, 3]) 
x.dtype

dtype('int32')

In [6]:
x = np.array([1.0, 2,0, 3,0]) 
x.dtype

dtype('float64')

In [8]:
a = np.array([[1, 2], [3, 4]])
print (a)
print(a.shape, a.ndim)

[[1 2]
 [3 4]]
(2, 2) 2


In [10]:
a=np.array([1, 2, 3, 4, 5], ndmin=2)
print (a, a.shape)
b=np.array([1, 2, 3, 4, 5], ndmin=1)
print (b, b.shape)

[[1 2 3 4 5]] (1, 5)
[1 2 3 4 5] (5,)


In [16]:
a = np.linspace(1.0, 2.0, num = 5, endpoint=True) 
print (a)
# a


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
a = np.arange(10) # == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
s = slice(2,7,2) # 2 ~ 7, 2씩 증가 
print (a, a[s], a[2:7:2])


[0 1 2 3 4 5 6 7 8 9] [2 4 6] [2 4 6]


In [21]:
a = np.arange(1, 11)
print(a)
print(a[1], a[[1, 5, 6]])

[ 1  2  3  4  5  6  7  8  9 10]
2 [2 6 7]


In [22]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x[1, 1]) # 2차원 배열 단일 값 인덱싱
y = x[[0,1,2], [0,1,0]] # 2차원 배열 다중 값 인덱싱
print (y)


4
[1 4 5]


In [23]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) 
z = x[1:4,1:3] # 1~4행, 1~3열
print (z)
y = x[1:4,[1,2]] #1 ~ 4행, 1, 2열
print (y)


[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [26]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
criterion = x > 5
print(criterion)
print(x[criterion])
# print(x[x > 5])

[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


In [28]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) # np.nan : 결측치(missing value)
print(~np.isnan(a))
print(a[~np.isnan(a)]) # ~ : not


[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [30]:
import pandas as pd

In [32]:
data = np.array(['a','b','c','d'])
# s = pd.Series(data)
s = pd.Series(data, index=[10, 20, 30, 40])
print(s)


10    a
20    b
30    c
40    d
dtype: object


In [36]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print(s[0], s[3:], sep="\n")
print(s['a'], s['a':'c'], sep="\n")


1
d    4
e    5
dtype: int64
1
a    1
b    2
c    3
dtype: int64


C:\Users\Administrator\AppData\Local\Temp\ipykernel_13480\1970323656.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0], s[3:], sep="\n")


In [38]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df


Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [41]:
data = { 'Name':['Tom', 'Jack', 'Steve', 'Ricky'],
         'Age':[28,34,29,42] }
# df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df = pd.DataFrame(data, index=[ 'rank {0}'.format(n) for n in range(4) ])
# df = pd.DataFrame(data)
df


Name  Age
rank 0    Tom   28
rank 1   Jack   34
rank 2  Steve   29
rank 3  Ricky   42

In [42]:
data = [ {'a': 1, 'b': 2},
         {'a': 5, 'b': 10, 'c': 20} ]
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [43]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
df2 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])
df1, df2


(        a   b
 first   1   2
 second  5  10,
         a  b1
 first   1 NaN
 second  5 NaN)

In [44]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df


one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [48]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df['one']
# df[0] # 오류 : 데이터프레임은 순서번호 인덱싱 사용 불가


a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [49]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df['three'] = pd.Series([10,20,30], index=['a','b','c'])
print(df)
df['four'] = df['one'] + df['three']
print(df)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


In [51]:
f = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
# print(df['b']) # 컬럼 b 검색
print(df.loc['b']) # 행 b 검색
print(df.loc['b', 'two']) # 행 b, 열 two 검색


one    2.0
two    2.0
Name: b, dtype: float64
2


In [60]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print(df.iloc[2]) # 순서번호 2번 행 조회
print(df.iloc[1, 0]) # 순서번호 1번 행, 순서번호 0번 열 조회
print(df.iloc[:, 0]) # 순서번호 모든 행, 순서번호 0번 열 조회


one    3.0
two    3.0
Name: c, dtype: float64
2.0
a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64


In [54]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
print(df[2:4]) # 데이터프레임 슬라이싱은 행 번호 기준


   one  two
c  3.0    3
d  NaN    4


In [69]:
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
# df = df.append(df2) # deprecated
df = pd.concat([df, df2], axis=0) # axis=0 : 행방향 결합, axis=1 : 열방향 결합
df = df.drop(0) # 행 인덱스 0번 행 삭제 ( 인덱스 != 순서번호 )
df = df.drop("a", axis=1) # 열 이름 "a" 열 삭제
print(df)


   b
1  4
1  8
