In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

array([122.02, 131.73, 130.6 , 131.82, 132.05, 126.12, 124.43, 132.89,
       122.79, 129.95, 126.14, 134.45, 127.64, 125.68])

In [5]:
# 연속형 데이터 1표본(1집단)에 대한 가설 검정

potato_df = pd.read_csv("data-files/potato.csv")
potato = potato_df['무게'].values
potato

print(potato.mean())

# 샘플링된 감자는 전국 감자 평균 품질보다 낮다 ( 무게가 작다 )

stats.ttest_1samp(potato, 130)


128.4507142857143


TtestResult(statistic=-1.4551960206404198, pvalue=0.16933464230414275, df=13)

In [11]:
# 연속형 데이터 2표본(2집단)에 대한 가설 검정 1

training_rel_df = pd.read_csv("data-files/training_rel.csv")
before, after = training_rel_df["전"].values, training_rel_df["후"].values
# print( before, after )
print( (after - before).mean() )

stats.ttest_ind(before, after), stats.ttest_rel(before, after)


5.4


(TtestResult(statistic=-1.8997443074539122, pvalue=0.0650756655596349, df=38.0),
 TtestResult(statistic=-2.204154108716127, pvalue=0.04004419061842953, df=19))

In [53]:
# 범주형 데이터 한 표본의 분포 검정

N = 10
K = 4
mu_0 = np.ones(K) / K
print(mu_0)

np.random.seed(42)
x = np.random.choice(K, N, p=mu_0) # 4개의 숫자를 각각 25% 확률로 10개 뽑기
print(x)
c = np.bincount(x)
print(c)

stats.chisquare(x)

[0.25 0.25 0.25 0.25]
[1 3 2 2 0 0 0 3 2 2]
[3 1 4 2]


Power_divergenceResult(statistic=8.333333333333332, pvalue=0.5009344477491052)

In [58]:
# 범주형 데이터 두 표본(두 속성)간 독립성 검정

ad_df = pd.read_csv('data-files/ad.csv')
ad_df

ad_stats = ad_df.groupby('광고')['구입'].value_counts()
ad_stats

print( ad_stats.iloc[1] / ad_stats.iloc[:2].sum() ) # A광고 구매율
print( ad_stats.iloc[3] / ad_stats.iloc[2:].sum() ) # B광고 구매율

ad_cross = pd.crosstab(ad_df["광고"], ad_df['구입'])
ad_cross

stats.chi2_contingency(ad_cross, correction=True)

0.1225
0.085


Chi2ContingencyResult(statistic=3.344907407407407, pvalue=0.06741327136707487, dof=1, expected_freq=array([[360.,  40.],
       [540.,  60.]]))

In [28]:
ad_cross

구입  하지 않았다  했다
광고            
A      351  49
B      549  51